### ISSUE TITLE
imperfect indentation on line 34 of HTML file?

### ISSUE THREAD

**Issue by awhetzel** [BoiseStateCS401/CS401-activity-404error#1]
This is a bit ticky tacky, but from around line 25-34 of your index.html file the indentation is a little wonky. See the screenshot below: 

![webfeedback](https://user-images.githubusercontent.com/30787823/30234936-38be3c7e-94b7-11e7-99f9-107c1dc8c7bb.PNG)

Nice website overall, it was hard to come up with an issue to post!

**Comment by joeb-bsu** [comment]
changed editors to one that would auto format and correct wonkieness
