### ISSUE TITLE
Pig pic not linking - Attribute src not allowed on element a

### ISSUE THREAD

**Issue by wesleygruenberg** [BoiseStateCS401/CS401-activity-404error#2]
From HTML checker: line 31 
	`<a src="https://en.wikipedia.org/wiki/Bacon" title="Future Bacon">↩	`

should be `<a href="https://en.wikipedia.org/wiki/Bacon" title="Future Bacon"><img src=....etc. ></a>`

This should fix the link problem and pass this portion of the HTML checker

**Comment by joeb-bsu** [comment]
fixed
